"""
Generated by 'django-admin startproject' using Django 1.9.12.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Application definition

INSTALLED_APPS = [
    # ... all django defaults
    'webpack_loader',
    'webpack_helper',
    # ... all your remaining apps
    'livereload' # ensures that django refreshes on any changes
]

MIDDLEWARE_CLASSES = [
    # ... all your other middleware
    'livereload.middleware.LiveReloadScript'
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/


STATIC_URL = '/static/'

# NOTE: All the settings below are already set to sensible
# defaults
WEBPACK_HELPER = {}

# The ocation of your node_modules (will be used to find webpack binary)
# Can be a relative or absolute path
WEBPACK_HELPER['NODE_MODULES'] = 'node_modules'

# the base output directory for webpack
# Can be a relative or absolute path
WEBPACK_HELPER['BASE_DIR'] = os.path.join(BASE_DIR, 'webpack')

# --- paths relative to WEBACK_HELPER['BASE_DIR']
# the folder that will be used to collect all webpack
# related output

# statistics generated by `webpack-bundle-tracker` (node app)
WEBACK_HELPER['STATS_DIR'] = 'stats/'
# static files (all files in here will be exposed to the internet by django)
WEBACK_HELPER['STATIC_DIR'] = 'static/'  
# webpack_helper generated configuration files go in here as `appname.json`
WEBACK_HELPER['CONFIG_DIR'] = 'config/'

# --- relative to STATIC_DIR!
# this is where webpack places your compiled bundles
WEBACK_HELPER['BUNDLE_DIR'] = 'bundles/'

# Where will the bundles live when we SERVE the website?
# Where will the contents of `static/bundles/` become visible?
# it can be a full URL
WEBPACK_HELPER['PUBLIC_PATH_BASE'] = STATIC_URL


# We do this so that django's collectstatic copies our bundles to the STATIC_ROOT 
# or syncs them to whatever storage we use.
STATICFILES_DIRS = [
    # ... all your other directories
] + [os.path.join(WEBPACK_HELPER['BASE_DIR'], WEBACK_HELPER['STATIC_DIR'])]

# NOTE You must add an entry below for each app you
# wish to include.
# See django-webpack-loader's documentation for more details
WEBPACK_LOADER = {
    'DEFAULT': {
        # bundles go here (relative to our static apps directory)
        # i.e. `bundle/` is inside the staticfiles dir {WEBPACK_BASE_DIR}/static/
        'BUNDLE_DIR_NAME': 'bundles/',

        # NOTE the stats file path is built as follows: {WEBPACK_BASE_DIR}/{WEBPACK_STATS_DIR}/{applabel}.json
        'STATS_FILE': os.path.join(WEBPACK_HELPER['BASE_DIR'], 'webpack/stats/applabel.json'),

    }
}
